### ISSUE TITLE
希望能指定 linkServer 所连接的 WebSocket 地址

### ISSUE THREAD

**Issue by MoonLeeeaf** [Circkoooooo/cqhttp-ts#1]
如题，能在调用[`linkServer`](https://github.com/yuanxin518/cqhttp-ts/blob/main/src/server/linkServer.ts#L38)时传入一个指定的服务器地址而非只是 localhost:[port]

例如这样：
```typescript
const initLinkServer = (port: number, server: string): Promise<GetLoginInfoApiResponseType> => {
	return new Promise((resolve, reject) => {
		CqWebsocket = new WebSocket('ws://' + server + ':' + port);
// 略去...
```

或者直接允许传入 [端口 / 整条地址]

至于为什么是开 Issue 而不是 PR，因为我不知道这样的变更会不会严重影响后续更新的使用者，而且我不会 TypeScript，这个项目的依赖库死活 install 不下来（）

ps:虽然我看两年没更新了，不过这个库还是挺好用的，感谢作者（）

**Comment by yuanxin518** [comment]
#2 打了个补丁，支持了
```typescript
declare function initLinkServer(port?: number, ip?: string): Promise<GetLoginInfoApiResponseType>;
declare function initLinkServer(fullPath?: string): Promise<GetLoginInfoApiResponseType>;
```

如果你感兴趣，你可以拉仓库代码，在你的分支进行修改然后npm run build编译，因为后期这个项目就不会维护了。

依赖库install不下来，那你可以用vpn，npm config set proxy=vpn本地代理地址（例如 http://127.0.0.1:7890）

**Comment by MoonLeeeaf** [comment]
谢谢🌚👍

**Comment by yuanxin518** [comment]
npm install cqhttp-ts@1.3.0 最新
